/* NEXORA event catalog and shared client-side state. */
window.Nexora = window.Nexora || {};
Nexora.events = [
 {id:'technova',title:'TECHNOVA',subtitle:'AI & Innovation Challenge',category:'Technical',date:'18 Oct 2026',time:'09:00 AM',venue:'Innovation Arena',capacity:300,registered:214,team:'1–3',prize:'₹20,000',color:'#4e6a51',art:'radial-gradient(circle at 70% 35%,#bbef813d,transparent 27%),linear-gradient(135deg,#17231c,#657849)',desc:'Build bold ideas with emerging technologies. Create an AI-powered solution that makes a meaningful difference.',rules:['Teams may include up to 3 students.','Bring your own laptop and charger.','Projects must be built during the event.'],organizer:'NEXORA Tech Council',contact:'technova@nexora.campus',schedule:'09:00 Opening · 10:00 Build · 16:00 Demo'},
 {id:'codefusion',title:'CODEFUSION 2026',subtitle:'The 24-Hour Hackathon',category:'Hackathons',date:'18 Oct 2026',time:'10:00 AM',venue:'Innovation Arena',capacity:500,registered:342,team:'2–4',prize:'₹50,000',color:'#455b40',art:'radial-gradient(circle at 70% 40%,#d7fa6350,transparent 32%),linear-gradient(135deg,#19251b,#526745)',desc:'A single night to turn bold ideas into things that matter. Build with a team, learn from mentors, and ship something extraordinary.',rules:['Teams must have 2–4 members.','All code must be created during the event.','Open-source tools and APIs are welcome.'],organizer:'NEXORA Developer Society',contact:'hello@codefusion.nexora.campus',schedule:'10:00 Kickoff · 13:00 Lunch · 18:00 Mentor review · 08:00 Final submission'},
 {id:'cyberwar',title:'CYBERWAR',subtitle:'Cybersecurity Challenge',category:'Technical',date:'20 Oct 2026',time:'11:00 AM',venue:'Cyber Lab',capacity:180,registered:168,team:'1–2',prize:'₹15,000',color:'#355b61',art:'radial-gradient(circle at 52% 42%,#85e5da70,transparent 27%),linear-gradient(135deg,#10242a,#356b70)',desc:'Think like a defender. A hands-on capture-the-flag challenge across forensics, web security, and cryptography.',rules:['Individual or pairs.','No external attack traffic.','Bring a laptop; lab systems are provided.'],organizer:'Cyber Security Club',contact:'cyber@nexora.campus',schedule:'11:00 Briefing · 11:30 Challenges · 16:00 Awards'},
 {id:'designverse',title:'DESIGNVERSE',subtitle:'UI/UX Design Battle',category:'Workshops',date:'19 Oct 2026',time:'01:00 PM',venue:'Design Studio',capacity:120,registered:76,team:'Individual',prize:'₹12,000',color:'#785d58',art:'radial-gradient(circle at 75% 30%,#f8bc9570,transparent 30%),linear-gradient(140deg,#41302b,#a5755d)',desc:'A fast-paced design sprint. Reimagine a familiar campus experience and present a prototype that people love using.',rules:['Individual competition.','Any design tool is welcome.','Final prototype must be presented in 5 minutes.'],organizer:'NEXORA Design Guild',contact:'design@nexora.campus',schedule:'13:00 Brief · 13:30 Sprint · 16:30 Showcase'},
 {id:'roborush',title:'ROBO RUSH',subtitle:'Robotics Competition',category:'Technical',date:'21 Oct 2026',time:'09:30 AM',venue:'Sports Complex',capacity:100,registered:63,team:'2–5',prize:'₹25,000',color:'#806a42',art:'radial-gradient(circle at 32% 35%,#f6da7c68,transparent 27%),linear-gradient(135deg,#352b1d,#917647)',desc:'Design, build, and race a robot through an unpredictable course. Precision and ingenuity decide the winner.',rules:['Teams of 2–5 students.','Robot must fit within 30 × 30 cm.','Components and batteries supplied on site.'],organizer:'Robotics Lab',contact:'robots@nexora.campus',schedule:'09:30 Inspection · 11:00 Qualifiers · 15:00 Finals'},
 {id:'startup-arena',title:'STARTUP ARENA',subtitle:'Entrepreneurship Pitch',category:'Entrepreneurship',date:'22 Oct 2026',time:'02:00 PM',venue:'Main Auditorium',capacity:150,registered:91,team:'1–4',prize:'₹30,000',color:'#6a5570',art:'radial-gradient(circle at 65% 38%,#d1a6ee60,transparent 28%),linear-gradient(135deg,#292031,#786087)',desc:'Pitch an idea that deserves to exist. Get feedback from founders and compete for seed support for your next step.',rules:['Teams may include up to 4 students.','Pitch deck limited to 8 slides.','Five minute pitch followed by Q&A.'],organizer:'NEXORA Entrepreneurship Cell',contact:'startups@nexora.campus',schedule:'14:00 Welcome · 14:30 Pitches · 17:00 Jury results'},
 {id:'battle-bands',title:'BATTLE OF BANDS',subtitle:'Live Music Competition',category:'Cultural',date:'23 Oct 2026',time:'06:00 PM',venue:'Open Air Theatre',capacity:800,registered:522,team:'3–8',prize:'₹20,000',color:'#76514d',art:'radial-gradient(circle at 52% 45%,#ff987080,transparent 28%),linear-gradient(135deg,#382424,#a95649)',desc:'The stage is yours. Original music, covers, and big energy under the open sky. Bring the sound your campus needs.',rules:['Bands of 3–8 members.','Performance time is 12 minutes.','All genres and original work welcome.'],organizer:'NEXORA Music Society',contact:'music@nexora.campus',schedule:'18:00 Doors · 18:30 Performances · 21:30 Winners'},
 {id:'pixel-perfect',title:'PIXEL PERFECT',subtitle:'Photography Challenge',category:'Cultural',date:'19 Oct 2026',time:'08:00 AM',venue:'Open Air Theatre',capacity:200,registered:153,team:'Individual',prize:'₹10,000',color:'#496574',art:'radial-gradient(circle at 70% 33%,#a9dfff70,transparent 26%),linear-gradient(135deg,#1e3038,#588095)',desc:'Find a story in the details. Explore the campus with a camera and capture the spirit of NEXORA in one frame.',rules:['Individual entry; phone or camera allowed.','Images must be captured on campus that day.','Basic color correction is allowed.'],organizer:'NEXORA Photography Club',contact:'photo@nexora.campus',schedule:'08:00 Brief · 08:30 Photo walk · 14:00 Submission'}
];
Nexora.categories=['All','Technical','Cultural','Sports','Workshops','Hackathons','Gaming','Entrepreneurship'];
Nexora.read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('nexora-'+key))??fallback}catch{return fallback}};
Nexora.write=(key,value)=>localStorage.setItem('nexora-'+key,JSON.stringify(value));
Nexora.registrations=Nexora.read('registrations',[]);Nexora.favorites=Nexora.read('favorites',[]);
